extends:
  - airbnb
  - prettier
env:
  jest: true
  browser: true
plugins:
  - prettier
rules:
  prettier/prettier:
    - error
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
  import/prefer-default-export: 0
  # warnings allow building in development mode but not merging into develop
  no-debugger: 1 # do allow debugger in development mode
  react/prop-types: 1 # don't enforce prop-type checking in development mode
  no-unused-vars: # allow unused vars in development mode. do allow unused function arguments in production. e.g. to show that a function matches a specific signature
    - warn
    - { 'vars': 'all', 'args': 'none', 'ignoreRestSiblings': true }
  react/no-unused-state: # allow unused state in development mode.
    - warn
  react/no-unused-prop-types: 1 # allow unused prop types in development mode
  no-sequences: 1 # allow sequences for debugging
