language: node_js
node_js:
  - 8
os:
  - linux
script: # determines the order everything runs in
  - npm test
  - npm run build
after_success:
  - chmod ugo+x ./scripts/deploy.sh
  - ./scripts/deploy.sh
