language: node_js
node_js:
  - 8
os:
  - linux
stages:  # determines the order everything runs in
- test
- deploy
jobs:  #  specifies the actual job
  include:
    - stage: test
      npm test
    - stage: deploy
      chmod ugo+x ./scripts/deploy.sh
      ./scripts/deploy.sh
